name: Hello # ワークフロー名
on: push    # イベント（プッシュ時に起動）
jobs:       # ジョブの定義
  hello:    # ジョブID
    run-on: ubuntu-latest        # ランナー（Ubuntuで実行）
    steps:
    - run: echo "Hello, world"
    - uses: actions/checkout@v4